### ISSUE TITLE
FLUO_DEV?

### ISSUE THREAD

**Issue by dhutchis** [astralway/uno#129]
Is `FLUO_DEV` meant to point to the location of this Github repo, or does it have a different meaning?

In fetch.sh and all the setup-*.sh files, I replaced 

```bash
source "$FLUO_DEV"/bin/impl/util.sh
```

with

```bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/../.."
source "$DIR"/bin/impl/util.sh
```

which gets the location of the Github repo, as long as the scripts are not moved or symlinked. I also changed `FLUO_DEV` to `DIR` when referenced.  Then the scripts worked.

**Comment by mikewalch** [comment]
Yes.  `FLUO_DEV` is meant to point to the root of the repo.  Uno used to be `fluo-dev`.  I guess this was missed in the rename.

**Comment by dhutchis** [comment]
What do you think of renaming to `UNO_DEV` and documenting?  Also, using the location of the script as above if `UNO_DEV` is not defined.

**Comment by mikewalch** [comment]
Sounds good to me `UNO_HOME` or `UNO_PREFIX` might make more sense but `UNO_DEV` works too.  

Did you want to make a pull request?  If not, I can assign it to myself and will try to get to it soon.

**Comment by dhutchis** [comment]
Let's go for `UNO_HOME`.  I'll work in a PR.
