### ISSUE TITLE
Mysterious File appears

### ISSUE THREAD

**Issue by milleruntime** [astralway/uno#135]
Whenever I do a "uno fetch accumulo" from my Uno directory, Uno will build Accumulo properly but a strange file (a.out) will show up in my Accumulo source directory under the assemble module. 
$ git status
On branch 1.8
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	assemble/a.out
nothing added to commit but untracked files present (use "git add" to track)

$ file assemble/a.out 
assemble/a.out: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked (uses shared libs), not stripped

$ strings assemble/a.out 
/lib/ld64.so.1
libhadoop.so.1.0.0
_edata
__bss_start
_end
.symtab
.strtab
.shstrtab
.interp
.hash
.dynsym
.dynstr
.eh_frame
.dynamic
_DYNAMIC
_GLOBAL_OFFSET_TABLE_
_edata
_end
_start
__bss_start

**Comment by milleruntime** [comment]
This may have been resolved with the latest version.  I am no longer seeing this file.  Although I am now using a Mac as a work machine. I will check on Ubuntu laptop to see if its still happening.

**Comment by milleruntime** [comment]
I just saw this file again on Ubuntu.  This time I didn't even compile through Uno.  From Accumulo 1.7.3.snapshot branch I ran:
mvn clean install -Pthrift -DskipTests -Dfindbugs.skip -Dcheckstyle.skip

**Comment by mikewalch** [comment]
This sounds like an Accumulo issue.  An issue should be created in Accumulo's JIRA and this ticket should be closed.
