### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by milleruntime** [astralway/uno#137]
I did a straight https clone of Uno master onto an AWS instance and ran using all the defaults.  It was unable to find Accumulo with the selected mirror.  Zookeeper and Hadoop used the same mirror and had no problem downloading the tars.

--2017-03-02 11:13:08--  http://mirrors.advancedhosters.com/apache//accumulo/1.8.0/accumulo-1.8.0-bin.tar.gz
Resolving mirrors.advancedhosters.com (mirrors.advancedhosters.com)... 46.229.166.133, 2a02:b48:6:1::2
Connecting to mirrors.advancedhosters.com (mirrors.advancedhosters.com)|46.229.166.133|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-03-02 11:13:08 ERROR 404: Not Found.

The tarball accumulo-1.8.0-bin.tar.gz does not exist in downloads/

**Comment by keith-turner** [comment]
Ah, since 1.8.1 was released then 1.8.0 is not available in the mirrors
