### ISSUE TITLE
Easy Way to get Hashes

### ISSUE THREAD

**Issue by milleruntime** [astralway/uno#166]
It would be really nice to have an easy way to populate the hash for Accumulo version other than 1.8.1.  Maybe a script or even just a command in the README.  I find myself never changing the version uno.conf and just building it locally because it is easier to just run "git checkout 1.7".

**Comment by keith-turner** [comment]
Could have 1.7.3 and 1.8.1 hashes with one commented out.

**Comment by keith-turner** [comment]
Could also have a bash switch stmt that switches on the Accumulo version and can set a few hashes.

**Comment by mikewalch** [comment]
I think this is a good idea.  Would be nice to do this for Hadoop and Zookeeper too.

**Comment by ctubbsii** [comment]
I like the idea of having a few commented out ones.
